### ISSUE TITLE
不能用啊 报错

### ISSUE THREAD

**Issue by fuya417061649** [okeyzero/suiProject#1]
throw new Error(
            ^

Error: Wrong secretKey size. Expected 32 bytes, got 35.

**Comment by fuya417061649** [comment]
![image](https://github.com/okeyzero/suiProject/assets/90825234/5fbc2774-a1fe-471e-81c0-6be05bafd71c)

**Comment by okeyzero** [comment]
用这个钱包
https://chrome.google.com/webstore/detail/efbglgofoippbgcjepnhiblaibcnclgk
